version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chats:/app/chats
      - ./code:/app/code
      - ./images:/app/images
      - ./knowledge_base:/app/knowledge_base
      - ./rag_storage:/app/rag_storage
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=Aa123456
      - POSTGRES_USER=gptadmin
      - POSTGRES_DB=gpt
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/

    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gpt.com
      - PGADMIN_DEFAULT_PASSWORD=Aa123456
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 